########## DON'T CHANGE OR DELETE THIS FILE ##########

[PATHS]
########## please don't change anything here ##########
uname = default

[FORMATS]
########## please don't change anything here ##########
uname = file

[PROGRAMS]
########## please don't change anything here ##########
uname = ['uname']

[VERSIONS]
########## please don't change anything here ##########
uname = 0.1

