[PATHS]
########## provide local paths for the dependencies here ##########
#### or change to a blank field if you don't need the program #####
abyss = default
blast = default
blat = default
bowtie2 = default
bwa = default
cap3 = default
cdhit = default
fastqc = default
multiqc = default
samtools = default
spades = default
trinity = default
transabyss = default

[FORMATS]
########## please don't change anything here ##########
abyss = file
blast = directory
blat = file
bowtie2 = directory
bwa = file
cap3 = file
cdhit = directory
fastqc = file
multiqc = file
samtools = file
spades = file
trinity = file
transabyss = file

[PROGRAMS]
########## please don't change anything here ##########
abyss = ['abyss-pe']
blast = ['makeblastdb', 'blastn', 'blastx', 'blastp', 'tblastn', 'tblastx']
blat = ['blat']
bowtie2 = ['bowtie2', 'bowtie2-build']
bwa = ['bwa']
cap3 = ['cap3']
cdhit = ['cd-hit-est']
fastqc = ['fastqc']
multiqc = ['multiqc']
samtools = ['samtools']
spades = ['spades']
trinity = ['Trinity']
transabyss = ['transabyss']

[VERSIONS]
########## optional dependency version check ##########
abyss = 2
blast = 2.7
blat = NA
bowtie2 = 2.2
bwa = 0.7
cap3 = NA
cdhit = 4.2
fastqc = 0.11
multiqc = 1.8
samtools = 1.7
spades = 3.0
trinity = 2.6
transabyss = 2

